#!/bin/tcsh
source hosts.csh

foreach x (mchamp100_separateEvents_particle0_725_updatedSim_fixedMatching mchamp200_separateEvents_particle0_725_updatedSim_fixedMatching mchamp300_separateEvents_particle0_725_updatedSim_fixedMatching mchamp400_separateEvents_particle0_725_updatedSim_fixedMatching mchamp500_separateEvents_particle0_725_updatedSim_fixedMatching mchamp600_separateEvents_particle0_725_updatedSim_fixedMatching mchamp700_separateEvents_particle0_725_updatedSim_fixedMatching mchamp700_separateEvents_particle0_2ndHalf_725_updatedSim_fixedMatching mchamp800_separateEvents_particle0_725_updatedSim_fixedMatching mchamp900_separateEvents_particle0_725_updatedSim_fixedMatching mchamp1000_separateEvents_particle0_725_updatedSim_fixedMatching)
    source $p"ListHaddStage.csh" $x > & "out_"$x &
end
