{
//=========Macro generated from canvas: c1/c1
//=========  (Wed Sep 16 10:49:21 2015) by ROOT version5.34/18
   TCanvas *c1 = new TCanvas("c1", "c1",18,41,1000,550);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c1->Range(-303.7975,-3.170732,1594.937,21.21951);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetGridx();
   c1->SetGridy();
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.16);
   c1->SetRightMargin(0.05);
   c1->SetTopMargin(0.05);
   c1->SetBottomMargin(0.13);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   c1->SetFrameFillStyle(0);
   c1->SetFrameBorderMode(0);
   
   TH2F *h1 = new TH2F("h1","",30,0,1500,20,0,20);
   h1->SetStats(0);
   h1->GetXaxis()->SetTitle("Number of Colliding Bunches");
   h1->GetXaxis()->SetLabelFont(42);
   h1->GetXaxis()->SetLabelOffset(0.007);
   h1->GetXaxis()->SetLabelSize(0.05);
   h1->GetXaxis()->SetTitleSize(0.06);
   h1->GetXaxis()->SetTitleOffset(0.9);
   h1->GetXaxis()->SetTitleFont(42);
   h1->GetYaxis()->SetTitle("HLT Rate [Hz]");
   h1->GetYaxis()->SetLabelFont(42);
   h1->GetYaxis()->SetLabelOffset(0.007);
   h1->GetYaxis()->SetLabelSize(0.05);
   h1->GetYaxis()->SetTitleSize(0.06);
   h1->GetYaxis()->SetTitleOffset(1.25);
   h1->GetYaxis()->SetTitleFont(42);
   h1->GetZaxis()->SetLabelFont(42);
   h1->GetZaxis()->SetLabelOffset(0.007);
   h1->GetZaxis()->SetLabelSize(0.05);
   h1->GetZaxis()->SetTitleSize(0.06);
   h1->GetZaxis()->SetTitleFont(42);
   h1->Draw("");
   
   TGraphErrors *gre = new TGraphErrors(4);
   gre->SetName("Graph0");
   gre->SetTitle(";Number of Colliding Bunches;HLT Rate [Hz]");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(20);
   gre->SetMarkerSize(1.3);
   gre->SetPoint(0,1368,3.7);
   gre->SetPointError(0,0,0.6);
   gre->SetPoint(1,807,9);
   gre->SetPointError(1,0,1);
   gre->SetPoint(2,471,13.5);
   gre->SetPointError(2,0,1.2);
   gre->SetPoint(3,72,17);
   gre->SetPointError(3,0,2);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","",100,0,1497.6);
   Graph_Graph1->SetMinimum(0);
   Graph_Graph1->SetMaximum(20);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);
   Graph_Graph1->GetXaxis()->SetTitle("Number of Colliding Bunches");
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph1->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetTitle("HLT Rate [Hz]");
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph1->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph1->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph1->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph1);
   
   gre->Draw("p");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph1");
   gre->SetTitle(";Number of Colliding Bunches;HLT Rate [Hz]");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(21);
   gre->SetMarkerSize(1.3);
   gre->SetPoint(0,4,0.02666667);
   gre->SetPointError(0,0,0.003333333);
   gre->SetPoint(1,28,0.3);
   gre->SetPointError(1,0,0.03333334);
   gre->SetPoint(2,72,1);
   gre->SetPointError(2,0,0.1666667);
   gre->SetPoint(3,249,3.333333);
   gre->SetPointError(3,0,0.6666667);
   gre->SetPoint(4,618,8.666667);
   gre->SetPointError(4,0,1);
   gre->SetPoint(5,1051,15);
   gre->SetPointError(5,0,1.666667);
   gre->SetPoint(6,1331,20);
   gre->SetPointError(6,0,2.666667);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","",100,0,1463.7);
   Graph_Graph2->SetMinimum(0);
   Graph_Graph2->SetMaximum(20);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);
   Graph_Graph2->GetXaxis()->SetTitle("Number of Colliding Bunches");
   Graph_Graph2->GetXaxis()->SetLabelFont(42);
   Graph_Graph2->GetXaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetXaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetXaxis()->SetTitleSize(0.06);
   Graph_Graph2->GetXaxis()->SetTitleOffset(0.9);
   Graph_Graph2->GetXaxis()->SetTitleFont(42);
   Graph_Graph2->GetYaxis()->SetTitle("HLT Rate [Hz]");
   Graph_Graph2->GetYaxis()->SetLabelFont(42);
   Graph_Graph2->GetYaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetYaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetYaxis()->SetTitleSize(0.06);
   Graph_Graph2->GetYaxis()->SetTitleOffset(1.25);
   Graph_Graph2->GetYaxis()->SetTitleFont(42);
   Graph_Graph2->GetZaxis()->SetLabelFont(42);
   Graph_Graph2->GetZaxis()->SetLabelOffset(0.007);
   Graph_Graph2->GetZaxis()->SetLabelSize(0.05);
   Graph_Graph2->GetZaxis()->SetTitleSize(0.06);
   Graph_Graph2->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph2);
   
   gre->Draw("p");
   TGaxis *gaxis = new TGaxis(1500,0,1500,20,0,6000,6,"+L");
   gaxis->SetLabelOffset(0.005);
   gaxis->SetLabelSize(0.04);
   gaxis->SetTickSize(0.03);
   gaxis->SetGridLength(0);
   gaxis->SetTitleOffset(1);
   gaxis->SetTitleSize(0.04);
   gaxis->SetTitleColor(1);
   gaxis->SetTitleFont(62);
   gaxis->SetLabelColor(2);
   gaxis->SetLineColor(2);
   gaxis->Draw();
   
   TLegend *leg = new TLegend(0.6,0.75,0.9,0.85,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(62);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Graph0","HLT Rate","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1.3);
   entry->SetTextFont(62);
   entry=leg->AddEntry("Graph1","Inst. Luminosity","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1.3);
   entry->SetTextFont(62);
   leg->Draw();
   TLatex *   tex = new TLatex(0.95,0.96,"8 TeV (8 TeV)");
tex->SetNDC();
   tex->SetTextAlign(31);
   tex->SetTextFont(42);
   tex->SetTextSize(0.03);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.16,0.96,"CMS");
tex->SetNDC();
   tex->SetTextFont(61);
   tex->SetTextSize(0.0375);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.2548,0.96,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.0285);
   tex->SetLineWidth(2);
   tex->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
