#!/bin/tcsh

cd stopToLB1100_100mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1100_40mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1100_5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p3mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p4mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p8mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_0p9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1200_1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1400_0p5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1500_0p1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1500_0p5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1500_0p8mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1500_60mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1500_6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1500_8mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1500_90mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1600_0p2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1600_0p3mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1600_0p9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1600_20mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1600_2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1700_0p6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1700_0p7mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1700_30mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_0p2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_0p6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_0p7mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_0p8mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_100mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_20mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_30mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_50mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_60mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_70mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_80mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB1800_90mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB400_0p2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB400_0p4mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB400_0p6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB400_0p7mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB400_0p8mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB400_9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_0p1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_0p2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_0p4mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_0p5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_0p9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_10mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB500_2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB600_8mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_0p1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_0p2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_0p3mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_0p5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_0p6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_0p9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_7mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_8mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_90mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB700_9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_0p1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_0p3mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_0p6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_0p9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_2mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_30mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_3mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB800_6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_0p1mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_0p5mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_0p6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_0p7mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_0p9mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_3mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_4mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_50mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_60mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_6mm
condor_submit condor_resubmit.sub
cd ..
cd stopToLB900_8mm
condor_submit condor_resubmit.sub
cd ..
